# Site settings
title: LiBlog
SEOTitle: LiBlog
header-img: img/hd.png
email: lijinrui299792458@qq.com
description: "Learn in the Blog!"
keyword: "Blog,Code"
url: "http://lijinrui299792458.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lijinrui299792458/lijinrui299792458.github.io.git" # you code repository
#icon: "img/hd.png"

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Learn in the Blog!"
sidebar-avatar: /img/my-avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
#weibo_username:     YunLambert
zhihu_username:     nayrl
github_username:    lijinrui299792458
#facebook_username:  YunLambert
#jianshu_username:   f7640a282211
#twitter_username:   yunyunlambert




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important




# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  # Github Application 1:
  clientID: 346099f75f710cf629a2                           #生成的clientID
  clientSecret: f44bef3663ab8952bd09bbb2eedf1e35fbf3308e    #生成的clientSecret
  # Github Application 2:
  #clientID: 63f7ddf6421f48c66dd3                           #生成的clientID
  # clientSecret: 0c1b390cd01159a7f9fd0e9ac213daa6683b39c1    #生成的clientSecret
  repo: lijinrui299792458.github.io    #仓库名称
  owner: lijinrui299792458    #github用户名
  admin: lijinrui299792458
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 8a222ec72ea0457c806087979bdc6024

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "博客园",
        href: "https://www.cnblogs.com/nayrl/"
    },{
        title: "洛谷博客",
        href: "https://www.luogu.com.cn/blog/nayrl/"
    },{
        title: "AcWing",
        href: "https://www.acwing.com/user/myspace/index/28364/"
    }
]
